<a href="https://colab.research.google.com/github/lathamithu/Techvolt-Intern/blob/master/Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report,confusion_matrix
%matplotlib inline

In [ ]:
train = pd.read_csv("train (1).csv")
test = pd.read_csv("test.csv")

In [ ]:
train.head()

battery_power  blue  clock_speed  ...  touch_screen  wifi  price_range
0            842     0          2.2  ...             0     1            1
1           1021     1          0.5  ...             1     0            2
2            563     1          0.5  ...             1     0            2
3            615     1          2.5  ...             0     0            2
4           1821     1          1.2  ...             1     0            1

[5 rows x 21 columns]

In [ ]:
for i in train.columns:
  print(i,train[i].corr(train['price_range']))

battery_power 0.20072261211373094
blue 0.0205728540614185
clock_speed -0.006605690881732072
dual_sim 0.01744447923722472
fc 0.021998207776904255
four_g 0.014771711417239368
int_memory 0.04443495938898744
m_dep 0.0008530365050864314
mobile_wt -0.030302171314386412
n_cores 0.004399274799457278
pc 0.03359930021353949
px_height 0.14885755500042175
px_width 0.16581750172625515
ram 0.9170457362649905
sc_h 0.022986073167424428
sc_w 0.038711271664484175
talk_time 0.021858871162374796
three_g 0.023611216880045034
touch_screen -0.03041107189821805
wifi 0.018784812012788994
price_range 1.0


In [ ]:
X = train.drop(['price_range'], axis = 1)
Y = train['price_range']
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.30, random_state = 1)

In [ ]:
tree = DecisionTreeClassifier()
tree.fit(x_train,y_train)
ypred = tree.predict(x_test)

In [ ]:
accuracy_score(y_test,ypred)

0.8466666666666667

In [ ]:
rmse = np.sqrt(mean_squared_error(y_test,ypred))
rmse

0.39157800414902433

In [ ]:
print(classification_report(y_test, ypred))

              precision    recall  f1-score   support

           0       0.92      0.81      0.86       135
           1       0.74      0.86      0.80       149
           2       0.85      0.80      0.82       168
           3       0.91      0.92      0.91       148

    accuracy                           0.85       600
   macro avg       0.85      0.85      0.85       600
weighted avg       0.85      0.85      0.85       600



In [ ]:
print(confusion_matrix(y_test,ypred))

[[110  25   0   0]
 [ 10 128  11   0]
 [  0  20 134  14]
 [  0   0  12 136]]


In [ ]:
X = test.iloc[:,1:]
X.head()

battery_power  blue  clock_speed  ...  three_g  touch_screen  wifi
0           1043     1          1.8  ...        0             1     0
1            841     1          0.5  ...        1             0     0
2           1807     1          2.8  ...        0             1     1
3           1546     0          0.5  ...        1             1     0
4           1434     0          1.4  ...        1             0     1

[5 rows x 20 columns]

In [ ]:
y_pred = tree.predict(X)
y_pred

array([3, 3, 3, 3, 1, 3, 3, 1, 3, 0, 3, 3, 0, 1, 3, 1, 2, 1, 3, 2, 0, 3,
       1, 1, 3, 0, 2, 0, 3, 0, 3, 0, 3, 0, 1, 1, 3, 1, 2, 1, 1, 2, 0, 0,
       0, 1, 0, 3, 1, 2, 1, 0, 3, 0, 3, 1, 3, 1, 0, 3, 3, 3, 0, 1, 1, 1,
       1, 3, 1, 2, 1, 2, 2, 3, 3, 0, 2, 1, 2, 3, 1, 3, 3, 0, 3, 0, 3, 1,
       3, 0, 1, 2, 3, 0, 2, 2, 1, 1, 1, 2, 1, 0, 0, 3, 1, 2, 1, 1, 2, 3,
       3, 2, 1, 3, 3, 3, 3, 2, 3, 0, 0, 3, 2, 1, 2, 0, 3, 3, 3, 2, 0, 2,
       1, 0, 3, 0, 2, 0, 3, 2, 1, 3, 1, 3, 3, 3, 3, 2, 2, 3, 2, 3, 1, 0,
       3, 2, 3, 3, 3, 3, 2, 2, 3, 3, 2, 3, 1, 0, 3, 0, 0, 0, 2, 0, 0, 1,
       1, 0, 1, 2, 1, 0, 0, 1, 2, 3, 2, 1, 0, 0, 0, 0, 0, 3, 1, 0, 2, 2,
       2, 3, 1, 2, 3, 3, 3, 2, 1, 0, 0, 0, 1, 2, 0, 2, 3, 3, 0, 2, 0, 3,
       1, 3, 2, 1, 0, 1, 0, 3, 0, 1, 0, 3, 2, 1, 2, 1, 3, 0, 3, 1, 2, 0,
       0, 2, 0, 3, 3, 3, 1, 1, 3, 0, 0, 2, 3, 3, 1, 3, 1, 0, 3, 2, 1, 2,
       3, 3, 3, 1, 0, 0, 2, 3, 1, 1, 3, 2, 0, 3, 0, 1, 2, 0, 0, 3, 2, 3,
       3, 2, 1, 3, 2, 2, 3, 2, 3, 0, 2, 0, 3, 3, 1,